version: '3.8'

services:
  laravel:
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
    image: code4romania/website-factory
    ports:
      - '8080:80'
    environment:
      APP_KEY: change_me
